# -*- coding: utf-8 -*-
"""
古文觀止 Author Data
Maps directory keywords → article metadata, and author names → biographical info.
Generated for all 267 articles (222 standard + 45 supplementary).
"""

# Maps directory keyword → { author, era, dynasty }
AUTHOR_MAP = {
    # ── 左傳（周文） ──────────────────────────────────────────────────────────
    "zhengbo-keduan":        {"author": "左丘明", "era": "《左傳·隱公元年》",   "dynasty": "周文"},
    "caogui-lunzhan":        {"author": "左丘明", "era": "《左傳·莊公十年》",   "dynasty": "周文"},
    "gongzhiqi":             {"author": "左丘明", "era": "《左傳·僖公五年》",   "dynasty": "周文"},
    "zhuwuzhi":              {"author": "左丘明", "era": "《左傳·僖公三十年》", "dynasty": "周文"},
    "jianshu":               {"author": "左丘明", "era": "《左傳·僖公三十三年》","dynasty": "周文"},
    "zhaogong":              {"author": "召公",   "era": "《國語·周語上》",     "dynasty": "周文"},
    "zhouguo-zhanguo":       {"author": "左丘明", "era": "《國語·周語》",       "dynasty": "周文"},
    # 補充左傳篇目
    "zhouzheng-jiaozhi":     {"author": "左丘明", "era": "《左傳·隱公三年》",   "dynasty": "周文"},
    "zhengzhuanggong":       {"author": "左丘明", "era": "《左傳·隱公十一年》", "dynasty": "周文"},
    "zangaibo":              {"author": "左丘明", "era": "《左傳·桓公二年》",   "dynasty": "周文"},
    "qihuan-xiabai":         {"author": "左丘明", "era": "《左傳·僖公九年》",   "dynasty": "周文"},
    "yinyi-sheng":           {"author": "左丘明", "era": "《左傳·僖公十五年》", "dynasty": "周文"},
    "sirenpi":               {"author": "左丘明", "era": "《左傳·僖公二十四年》","dynasty": "周文"},
    "zhengzijia":            {"author": "左丘明", "era": "《左傳·宣公十二年》", "dynasty": "周文"},
    "wangsunman":            {"author": "左丘明", "era": "《左傳·宣公三年》",   "dynasty": "周文"},
    "qiguo-zuo":             {"author": "左丘明", "era": "《左傳·成公二年》",   "dynasty": "周文"},
    "chu-gui-jin":           {"author": "左丘明", "era": "《左傳·成公三年》",   "dynasty": "周文"},
    "lvxiang":               {"author": "左丘明", "era": "《左傳·成公十三年》", "dynasty": "周文"},
    "juzhi":                 {"author": "左丘明", "era": "《左傳·襄公十四年》", "dynasty": "周文"},
    "qixi":                  {"author": "左丘明", "era": "《左傳·襄公二十一年》","dynasty": "周文"},
    "zichan-qingbi":         {"author": "左丘明", "era": "《左傳·襄公二十四年》","dynasty": "周文"},
    "zichan-huaiyuan":       {"author": "左丘明", "era": "《左傳·昭公五年》",   "dynasty": "周文"},
    "zichan-yinhe":          {"author": "左丘明", "era": "《左傳·昭公十九年》", "dynasty": "周文"},
    "zichan-quechu":         {"author": "左丘明", "era": "《左傳·昭公元年》",   "dynasty": "周文"},
    "zige":                  {"author": "左丘明", "era": "《左傳·昭公十二年》", "dynasty": "周文"},
    "zichan-kuanmeng":       {"author": "左丘明", "era": "《左傳·昭公二十年》", "dynasty": "周文"},
    "stiqibo":               {"author": "左丘明", "era": "《左傳·隱公五年》",   "dynasty": "周文"},
    "jiliang":               {"author": "左丘明", "era": "《左傳·桓公六年》",   "dynasty": "周文"},
    "qihuan-gong":           {"author": "左丘明", "era": "《左傳·僖公四年》",   "dynasty": "周文"},
    "ziyu":                  {"author": "左丘明", "era": "《左傳·僖公二十二年》","dynasty": "周文"},
    "jiezhitui":             {"author": "左丘明", "era": "《左傳·僖公二十四年》","dynasty": "周文"},
    "yanzi":                 {"author": "左丘明", "era": "《左傳·襄公二十五年》","dynasty": "周文"},
    "jizha":                 {"author": "左丘明", "era": "《左傳·襄公二十九年》","dynasty": "周文"},
    "zhanxi":                {"author": "左丘明", "era": "《左傳·僖公二十六年》","dynasty": "周文"},
    # 額外補充左傳
    "zichan-buhuixiangxiao": {"author": "左丘明", "era": "《左傳·襄公三十一年》","dynasty": "周文"},
    "stiqibo-jian-guanyu":   {"author": "左丘明", "era": "《左傳·隱公五年》",   "dynasty": "周文"},
    "stiqibo-2":             {"author": "左丘明", "era": "《左傳·隱公五年》",   "dynasty": "周文"},

    # ── 國語（周文） ──────────────────────────────────────────────────────────
    "wu-xu-yue":             {"author": "左丘明", "era": "《國語·吳語》",       "dynasty": "周文"},
    "jigong-jianzhen-quanrong":{"author": "左丘明","era": "《國語·周語上》",    "dynasty": "周文"},
    "zhaogong-jian-liwang":  {"author": "左丘明", "era": "《國語·周語上》",     "dynasty": "周文"},
    "xiangwang-buxu-qingsui":{"author": "左丘明", "era": "《國語·周語中》",     "dynasty": "周文"},
    "danzi-zhi-chen":        {"author": "左丘明", "era": "《國語·周語下》",     "dynasty": "周文"},
    "zhanqin-lun-si-yuanju": {"author": "左丘明", "era": "《國語·魯語上》",     "dynasty": "周文"},
    "lige-duangu-kuangjun":  {"author": "左丘明", "era": "《國語·魯語上》",     "dynasty": "周文"},
    "jingjiang-lun-lao-yi":  {"author": "左丘明", "era": "《國語·魯語下》",     "dynasty": "周文"},
    "shuxiang-he-pin":       {"author": "左丘明", "era": "《國語·晉語八》",     "dynasty": "周文"},
    "wangsun-yu-lun-chubao": {"author": "左丘明", "era": "《國語·楚語下》",     "dynasty": "周文"},
    "zhuji-ying-xingcheng-yuwu":{"author": "左丘明","era": "《國語·越語上》",   "dynasty": "周文"},
    "shenxu-jian-xu-yuecheng":{"author": "左丘明", "era": "《國語·越語下》",    "dynasty": "周文"},
    "jingjiang":             {"author": "左丘明", "era": "《國語·魯語下》",     "dynasty": "周文"},

    # ── 公羊傳（周文） ────────────────────────────────────────────────────────
    "chunwang-zhengyue":     {"author": "公羊高", "era": "《公羊傳·隱公元年》", "dynasty": "周文"},
    "songren-ji-churen-ping":{"author": "公羊高", "era": "《公羊傳·宣公十五年》","dynasty": "周文"},

    # ── 穀梁傳（周文） ────────────────────────────────────────────────────────
    "wuzi-shi-zha-lai-pin":  {"author": "穀梁赤", "era": "《穀梁傳·襄公二十九年》","dynasty": "周文"},
    "zhengbo-keduan-yuyan":  {"author": "穀梁赤", "era": "《穀梁傳·隱公元年》", "dynasty": "周文"},
    "yushi-jinshi-mie-xiayang":{"author": "穀梁赤","era": "《穀梁傳·僖公二年》","dynasty": "周文"},

    # ── 禮記（周文） ──────────────────────────────────────────────────────────
    "jinxiangong-sha-shizi": {"author": "戴聖",   "era": "《禮記·檀弓下》",    "dynasty": "周文"},
    "zengzi-yi-ze":          {"author": "戴聖",   "era": "《禮記·檀弓上》",    "dynasty": "周文"},
    "youzi-zhi-yan-si-fuzi": {"author": "戴聖",   "era": "《禮記·檀弓上》",    "dynasty": "周文"},
    "gongzi-zhonger-dui-qinke":{"author": "戴聖", "era": "《禮記·檀弓下》",    "dynasty": "周文"},
    "du-kui-yang-zhi":       {"author": "戴聖",   "era": "《禮記·檀弓下》",    "dynasty": "周文"},
    "jinxianwenzi-cheng-shi":{"author": "戴聖",   "era": "《禮記·檀弓下》",    "dynasty": "周文"},

    # ── 石碏（周文，左傳轉述） ────────────────────────────────────────────────
    "shique":                {"author": "左丘明", "era": "《左傳·隱公三年》",   "dynasty": "周文"},
    "zangxibo":              {"author": "左丘明", "era": "《左傳·隱公五年》",   "dynasty": "周文"},
    "stiqibo-jian":          {"author": "左丘明", "era": "《左傳·隱公三年》",   "dynasty": "周文"},

    # ── 戰國策（秦文） ────────────────────────────────────────────────────────
    "zouji":                 {"author": "劉向",   "era": "《戰國策·齊策一》",   "dynasty": "秦文"},
    "chuzhe":                {"author": "劉向",   "era": "《戰國策·趙策四》",   "dynasty": "秦文"},
    "fengxuan":              {"author": "劉向",   "era": "《戰國策·齊策四》",   "dynasty": "秦文"},
    "jianzhuke":             {"author": "李斯",   "era": "《史記·李斯列傳》",   "dynasty": "秦文"},
    "suqin":                 {"author": "劉向",   "era": "《戰國策·秦策一》",   "dynasty": "秦文"},
    "simacuo":               {"author": "劉向",   "era": "《戰國策·秦策一》",   "dynasty": "秦文"},
    "zhaoweihou":            {"author": "劉向",   "era": "《戰國策·齊策四》",   "dynasty": "秦文"},
    # 補充戰國策
    "sujin-yi-lianheng-shuo-qin":{"author": "劉向","era": "《戰國策·秦策一》",  "dynasty": "秦文"},
    "simacuo-lun-fa-shu":    {"author": "劉向",   "era": "《戰國策·秦策一》",   "dynasty": "秦文"},
    "fanju-shuo-qinwang":    {"author": "劉向",   "era": "《戰國策·秦策三》",   "dynasty": "秦文"},
    "zouji-feng-qi-wang":    {"author": "劉向",   "era": "《戰國策·齊策一》",   "dynasty": "秦文"},
    "yanchu-shuo-qi-wang":   {"author": "劉向",   "era": "《戰國策·齊策四》",   "dynasty": "秦文"},
    "feng-xuan-ke-mengchangjun":{"author": "劉向", "era": "《戰國策·齊策四》",  "dynasty": "秦文"},
    "zhaowei-hou-wen-qi-shi":{"author": "劉向",   "era": "《戰國策·齊策四》",   "dynasty": "秦文"},
    "zhuangxin-lun-xingchen":{"author": "劉向",   "era": "《戰國策·楚策四》",   "dynasty": "秦文"},
    "chuzhe-shuo-zhao-taihou":{"author": "劉向",  "era": "《戰國策·趙策四》",   "dynasty": "秦文"},
    "luzhonglian-yi-bu-di-qin":{"author": "劉向", "era": "《戰國策·趙策三》",   "dynasty": "秦文"},
    "lugonggong-ze-yan":     {"author": "劉向",   "era": "《戰國策·魏策四》",   "dynasty": "秦文"},
    "tangju-shuo-xinlingjun":{"author": "劉向",   "era": "《戰國策·魏策四》",   "dynasty": "秦文"},
    "tangju-bu-ru-shi-ming": {"author": "劉向",   "era": "《戰國策·魏策四》",   "dynasty": "秦文"},
    "yue-yi-bao-yan-wang-shu":{"author": "樂毅",  "era": "《戰國策·燕策二》",   "dynasty": "秦文"},
    "lisi-jian-zhu-ke-shu":  {"author": "李斯",   "era": "《史記·李斯列傳》",   "dynasty": "秦文"},

    # ── 楚辭（秦文） ──────────────────────────────────────────────────────────
    "buju":                  {"author": "屈原",   "era": "《楚辭·卜居》",       "dynasty": "秦文"},
    "chuci-bu-ju":           {"author": "屈原",   "era": "《楚辭·卜居》",       "dynasty": "秦文"},
    "songyu-dui-chu-wang-wen":{"author": "宋玉",  "era": "《宋玉集》",          "dynasty": "秦文"},

    # ── 司馬遷（漢文） ────────────────────────────────────────────────────────
    "boyi":                  {"author": "司馬遷", "era": "《史記·伯夷列傳》",   "dynasty": "漢文"},
    "quyuan":                {"author": "司馬遷", "era": "《史記·屈原賈生列傳》","dynasty": "漢文"},
    "huaji":                 {"author": "司馬遷", "era": "《史記·滑稽列傳》",   "dynasty": "漢文"},
    "wudi-benji-zan":        {"author": "司馬遷", "era": "《史記·五帝本紀》",   "dynasty": "漢文"},
    "xiangyu-benji-zan":     {"author": "司馬遷", "era": "《史記·項羽本紀》",   "dynasty": "漢文"},
    "qinchu-zhi-ji-yue-biao":{"author": "司馬遷", "era": "《史記·秦楚之際月表》","dynasty": "漢文"},
    "gaozu-gongchen-hou-nianbiao":{"author": "司馬遷","era": "《史記·高祖功臣侯年表》","dynasty": "漢文"},
    "kongzi-shi-jia-zan":    {"author": "司馬遷", "era": "《史記·孔子世家》",   "dynasty": "漢文"},
    "waiqi-shi-jia-xu":      {"author": "司馬遷", "era": "《史記·外戚世家》",   "dynasty": "漢文"},
    "boyi-liezhuan":         {"author": "司馬遷", "era": "《史記·伯夷列傳》",   "dynasty": "漢文"},
    "guanyan-liezhuan":      {"author": "司馬遷", "era": "《史記·管晏列傳》",   "dynasty": "漢文"},
    "quyuan-liezhuan":       {"author": "司馬遷", "era": "《史記·屈原賈生列傳》","dynasty": "漢文"},
    "kuli-liezhuan-xu":      {"author": "司馬遷", "era": "《史記·酷吏列傳》",   "dynasty": "漢文"},
    "youxia-liezhuan-xu":    {"author": "司馬遷", "era": "《史記·游俠列傳》",   "dynasty": "漢文"},
    "huaji-liezhuan":        {"author": "司馬遷", "era": "《史記·滑稽列傳》",   "dynasty": "漢文"},
    "huozhi-liezhuan-xu":    {"author": "司馬遷", "era": "《史記·貨殖列傳》",   "dynasty": "漢文"},
    "taishigong-zixu":       {"author": "司馬遷", "era": "《史記·太史公自序》", "dynasty": "漢文"},
    "bao-ren-an-shu":        {"author": "司馬遷", "era": "《漢書·司馬遷傳》",   "dynasty": "漢文"},
    "baoren":                {"author": "司馬遷", "era": "《漢書·司馬遷傳》",   "dynasty": "漢文"},

    # ── 漢代詔令（漢文） ──────────────────────────────────────────────────────
    "gaodi-qiu-xian-zhao":   {"author": "劉邦",   "era": "《漢書·高帝紀》",    "dynasty": "漢文"},
    "wendi-yi-zuo-baixing-zhao":{"author": "劉恆", "era": "《漢書·文帝紀》",    "dynasty": "漢文"},
    "jingdi-ling-erqianshi-xiuzhi-zhao":{"author": "劉啟","era": "《漢書·景帝紀》","dynasty": "漢文"},
    "wudi-qiu-maocai-yideng-zhao":{"author": "劉徹","era": "《漢書·武帝紀》",   "dynasty": "漢文"},

    # ── 賈誼（漢文） ──────────────────────────────────────────────────────────
    "jiayi-guo-qin-lun-shang":{"author": "賈誼",  "era": "《新書·過秦論》",    "dynasty": "漢文"},
    "jiayi-zhi-an-ce-yi":    {"author": "賈誼",   "era": "《漢書·賈誼傳》",    "dynasty": "漢文"},
    "guoqin-repeat":         {"author": "賈誼",   "era": "《新書·過秦論》",    "dynasty": "漢文"},

    # ── 晁錯（漢文） ──────────────────────────────────────────────────────────
    "chaocuo-lun-guisu-shu":  {"author": "晁錯",  "era": "《漢書·食貨志》",    "dynasty": "漢文"},

    # ── 鄒陽（漢文） ──────────────────────────────────────────────────────────
    "zouyang-yuzhong-shang-liangwang-shu":{"author": "鄒陽","era": "《文選》",   "dynasty": "漢文"},
    "yuzhong":               {"author": "鄒陽",   "era": "《文選·鄒陽獄中上梁王書》","dynasty": "漢文"},

    # ── 司馬相如（漢文） ──────────────────────────────────────────────────────
    "simaxiangru-shangshu-jian-lie":{"author": "司馬相如","era": "《史記·司馬相如列傳》","dynasty": "漢文"},

    # ── 李陵（漢文） ──────────────────────────────────────────────────────────
    "da-suwu":               {"author": "李陵",   "era": "《文選·答蘇武書》",   "dynasty": "漢文"},
    "liling-da-suwu-shu":    {"author": "李陵",   "era": "《文選·答蘇武書》",   "dynasty": "漢文"},

    # ── 路溫舒（漢文） ────────────────────────────────────────────────────────
    "shangde":               {"author": "路溫舒", "era": "《漢書·路溫舒傳》",   "dynasty": "漢文"},
    "luwenshu-shangde-huanxing-shu":{"author": "路溫舒","era": "《漢書·路溫舒傳》","dynasty": "漢文"},

    # ── 楊惲（漢文） ──────────────────────────────────────────────────────────
    "bao-sunhuizong":        {"author": "楊惲",   "era": "《漢書·楊惲傳》",    "dynasty": "漢文"},
    "yangyun-bao-sun-huizong-shu":{"author": "楊惲","era": "《漢書·楊惲傳》",   "dynasty": "漢文"},

    # ── 光武帝（漢文） ────────────────────────────────────────────────────────
    "guangwudi-linzi-lao-geng-yan":{"author": "劉秀","era": "《後漢書·光武帝紀》","dynasty": "漢文"},

    # ── 馬援（漢文） ──────────────────────────────────────────────────────────
    "mayuan-jie-xiongzi-yandun-shu":{"author": "馬援","era": "《後漢書·馬援傳》","dynasty": "漢文"},

    # ── 諸葛亮（漢文） ────────────────────────────────────────────────────────
    "chushi":                {"author": "諸葛亮", "era": "《三國志·諸葛亮傳》", "dynasty": "漢文"},
    "zhuge-liang-qian-chushi-biao":{"author": "諸葛亮","era": "《三國志·諸葛亮傳》","dynasty": "漢文"},
    "zhuge-liang-hou-chushi-biao":{"author": "諸葛亮","era": "《三國志·諸葛亮傳》","dynasty": "漢文"},

    # ── 六朝文 ────────────────────────────────────────────────────────────────
    "chenqing":              {"author": "李密",   "era": "《晉書·李密傳》",    "dynasty": "六朝文"},
    "lanting":               {"author": "王羲之", "era": "《晉書·王羲之傳》",  "dynasty": "六朝文"},
    "guiqulai":              {"author": "陶淵明", "era": "《陶淵明集》",        "dynasty": "六朝文"},
    "taohuayuan":            {"author": "陶淵明", "era": "《陶淵明集》",        "dynasty": "六朝文"},
    "wuliu":                 {"author": "陶淵明", "era": "《陶淵明集》",        "dynasty": "六朝文"},
    "beishan":               {"author": "孔稚珪", "era": "《文選·北山移文》",  "dynasty": "六朝文"},
    # 補充六朝
    "limi-chenqing-biao":    {"author": "李密",   "era": "《晉書·李密傳》",    "dynasty": "六朝文"},
    "wangxizhi-lanting-ji-xu":{"author": "王羲之","era": "《晉書·王羲之傳》",  "dynasty": "六朝文"},
    "taoyuanming-guiqu-lai-ci":{"author": "陶淵明","era": "《陶淵明集》",       "dynasty": "六朝文"},
    "taoyuanming-taohua-yuan-ji":{"author": "陶淵明","era": "《陶淵明集》",     "dynasty": "六朝文"},
    "taoyuanming-wuliu-xiansheng-zhuan":{"author": "陶淵明","era": "《陶淵明集》","dynasty": "六朝文"},
    "kongzhigui-beishan-yiwen":{"author": "孔稚珪","era": "《文選·北山移文》", "dynasty": "六朝文"},

    # ── 唐文 ─────────────────────────────────────────────────────────────────
    "jianzong":              {"author": "魏徵",   "era": "《舊唐書·魏徵傳》",  "dynasty": "唐文"},
    "taizong-shi-si":        {"author": "魏徵",   "era": "《舊唐書·魏徵傳》",  "dynasty": "唐文"},
    "weizheng-jian-taizong-shi-si-shu":{"author": "魏徵","era": "《舊唐書·魏徵傳》","dynasty": "唐文"},
    "taowu-ze":              {"author": "駱賓王", "era": "《文苑英華》",        "dynasty": "唐文"},
    "luobinwang-tao-wu-zhao-xi":{"author": "駱賓王","era": "《文苑英華》",      "dynasty": "唐文"},
    "tengwangge":            {"author": "王勃",   "era": "《王子安集》",        "dynasty": "唐文"},
    "wangbo-tengwang-ge-xu": {"author": "王勃",   "era": "《王子安集》",        "dynasty": "唐文"},
    "yu-hanjingzhou":        {"author": "李白",   "era": "《李太白全集》",      "dynasty": "唐文"},
    "libai-yu-hanjingzhou-shu":{"author": "李白", "era": "《李太白全集》",      "dynasty": "唐文"},
    "libai-chunye-yan-taoli-yuan-xu":{"author": "李白","era": "《李太白全集》",  "dynasty": "唐文"},
    "lihua-diao-gu-zhanchang-wen":{"author": "李華","era": "《全唐文》",        "dynasty": "唐文"},
    "liuyuxi-lou-shi-ming":  {"author": "劉禹錫", "era": "《劉禹錫集》",        "dynasty": "唐文"},
    "dumu-efang-gong-fu":    {"author": "杜牧",   "era": "《樊川文集》",        "dynasty": "唐文"},
    "efang":                 {"author": "杜牧",   "era": "《樊川文集》",        "dynasty": "唐文"},
    "yuandao":               {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "mashuo":                {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "song-liyuan":           {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "jinxuejie":             {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "jishier":               {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "shiyue":                {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    # 韓愈補充
    "hanyu-yuan-dao":        {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-yuan-hui":        {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-huo-lin-jie":     {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-za-shuo-yi":      {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-za-shuo-si":      {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-shi-shuo":        {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-jinxue-jie":      {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-wuzhe-wangchengfu-zhuan":{"author": "韓愈","era": "《昌黎先生集》",  "dynasty": "唐文"},
    "hanyu-hui-bian":        {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-zhengchen-lun":   {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-hou-shi-jiu-ri-fu-shang-zaixiang-shu":{"author": "韓愈","era": "《昌黎先生集》","dynasty": "唐文"},
    "hanyu-hou-nian-jiu-ri-fu-shang-zaixiang-shu":{"author": "韓愈","era": "《昌黎先生集》","dynasty": "唐文"},
    "hanyu-yu-yuxiangyang-shu":{"author": "韓愈", "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-yu-chen-jishi-shu":{"author": "韓愈",  "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-ying-kemu-shi-yu-ren-shu":{"author": "韓愈","era": "《昌黎先生集》", "dynasty": "唐文"},
    "hanyu-song-mengdongye-xu":{"author": "韓愈", "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-song-liyuan-gui-pangu-xu":{"author": "韓愈","era": "《昌黎先生集》", "dynasty": "唐文"},
    "hanyu-song-dongshaonan-xu":{"author": "韓愈","era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-song-yangshaoyin-xu":{"author": "韓愈","era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-song-shi-chushi-xu":{"author": "韓愈", "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-song-wenchushi-fu-heyang-xu":{"author": "韓愈","era": "《昌黎先生集》","dynasty": "唐文"},
    "hanyu-ji-shi-er-lang-wen":{"author": "韓愈", "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-ji-e-yu-wen":     {"author": "韓愈",   "era": "《昌黎先生集》",      "dynasty": "唐文"},
    "hanyu-liuzihou-muzhi-ming":{"author": "韓愈","era": "《昌黎先生集》",      "dynasty": "唐文"},
    # 柳宗元
    "bushezhe":              {"author": "柳宗元", "era": "《柳河東集》",        "dynasty": "唐文"},
    "zhongshu":              {"author": "柳宗元", "era": "《柳河東集》",        "dynasty": "唐文"},
    "yuxi":                  {"author": "柳宗元", "era": "《柳河東集》",        "dynasty": "唐文"},
    "liuzongyuan-bo-fuchou-yi":{"author": "柳宗元","era": "《柳河東集》",       "dynasty": "唐文"},
    "liuzongyuan-tongye-fengdi-bian":{"author": "柳宗元","era": "《柳河東集》",  "dynasty": "唐文"},
    "liuzongyuan-jizi-bei":  {"author": "柳宗元", "era": "《柳河東集》",        "dynasty": "唐文"},
    "liuzongyuan-ziren-zhuan":{"author": "柳宗元","era": "《柳河東集》",        "dynasty": "唐文"},
    "liuzongyuan-yongzhou-weishijun-xintang-ji":{"author": "柳宗元","era": "《柳河東集》","dynasty": "唐文"},
    "liuzongyuan-gumu-tanxi-xiaoqiu-ji":{"author": "柳宗元","era": "《柳河東集》","dynasty": "唐文"},
    "liuzongyuan-xiaoshi-chengshan-ji":{"author": "柳宗元","era": "《柳河東集》","dynasty": "唐文"},
    "liuzongyuan-he-jinshi-wangcanyuan-shihuo-shu":{"author": "柳宗元","era": "《柳河東集》","dynasty": "唐文"},
    # 其他唐文
    "changgang":             {"author": "王禹偁", "era": "《小畜集》",          "dynasty": "唐文"},

    # ── 宋文 ─────────────────────────────────────────────────────────────────
    "wangyucheng-dai-lou-yuan-ji":{"author": "王禹偁","era": "《小畜集》",      "dynasty": "宋文"},
    "yueyang":               {"author": "范仲淹", "era": "《范文正公集》",      "dynasty": "宋文"},
    "zuiong":                {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "qiusheng":              {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "longgang":              {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "zongqin":               {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "du-mengchang":          {"author": "王安石", "era": "《臨川先生文集》",    "dynasty": "宋文"},
    "you-baochanshan":       {"author": "王安石", "era": "《臨川先生文集》",    "dynasty": "宋文"},
    "liuguo":                {"author": "蘇洵",   "era": "《嘉祐集》",          "dynasty": "宋文"},
    "chibifu":               {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "hou-chibifu":           {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "shizhongshan":          {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "fangshanzi":            {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "kuaizaiting":           {"author": "蘇轍",   "era": "《欒城集》",          "dynasty": "宋文"},
    "yiliwen":               {"author": "王褒",   "era": "《全唐文》",          "dynasty": "唐文"},
    "ligefei-shu-luoyang-mingyuan-ji-hou":{"author": "李格非","era": "《洛陽名園記》","dynasty": "宋文"},
    "simaguang-jian-yuan-ti-ming-ji":{"author": "司馬光","era": "《溫國文正司馬公文集》","dynasty": "宋文"},
    "qiangongfu-yi-tian-ji": {"author": "范仲淹", "era": "《范文正公集》",      "dynasty": "宋文"},
    "ligou-yuanzhou-zhouxue-ji":{"author": "李覯","era": "《直講李先生文集》",  "dynasty": "宋文"},
    "ouyangxiu-shi-miyan-shiji-xu":{"author": "歐陽修","era": "《歐陽文忠公集》","dynasty": "宋文"},
    # 歐陽修補充
    "yanjianxian-ci-tang-ji":{"author": "范仲淹", "era": "《范文正公集》",      "dynasty": "宋文"},
    "pengdang-lun":          {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "meishengyu-shiji-xu":   {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "song-yangzhi-xu":       {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "wudaishi-lingguan-zhuan-xu":{"author": "歐陽修","era": "《新五代史》",     "dynasty": "宋文"},
    "wudaishi-huanzhe-zhuan-lun":{"author": "歐陽修","era": "《新五代史》",     "dynasty": "宋文"},
    "xiangzhou-zhoujin-tang-ji":{"author": "歐陽修","era": "《歐陽文忠公集》",  "dynasty": "宋文"},
    "fengle-ting-ji":        {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "ji-shimanqing-wen":     {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    "guanzhong-lun":         {"author": "歐陽修", "era": "《歐陽文忠公集》",    "dynasty": "宋文"},
    # 蘇洵補充
    "xinshu":                {"author": "蘇洵",   "era": "《嘉祐集》",          "dynasty": "宋文"},
    "bianjian":              {"author": "蘇洵",   "era": "《嘉祐集》",          "dynasty": "宋文"},
    "zhang-yizhou-huaxiang-ji":{"author": "蘇洵","era": "《嘉祐集》",          "dynasty": "宋文"},
    # 蘇軾補充
    "xingshang-zhonghou-zhi-lun":{"author": "蘇軾","era": "《東坡全集》",       "dynasty": "宋文"},
    "fanzeng-lun":           {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "liuhou-lun":            {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "jiayi-lun":             {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "chaocuo-lun":           {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "shang-mei-zhijiang-shu":{"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "xiyu-ting-ji":          {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "lingxu-tai-ji":         {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "chaoran-tai-ji":        {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "fanghe-ting-ji":        {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    "chaozhou-han-wengong-miao-bei":{"author": "蘇軾","era": "《東坡全集》",    "dynasty": "宋文"},
    "qi-jiaozheng-luzhi-zouyi":{"author": "蘇軾", "era": "《東坡全集》",        "dynasty": "宋文"},
    "sanhuai-tang-ming":     {"author": "蘇軾",   "era": "《東坡全集》",        "dynasty": "宋文"},
    # 蘇轍補充
    "shang-shumi-han-taiwei-shu":{"author": "蘇轍","era": "《欒城集》",         "dynasty": "宋文"},
    # 王安石補充
    "da-sima":               {"author": "王安石", "era": "《臨川先生文集》",    "dynasty": "宋文"},
    "tongxue-yi-shou-bie-zigu":{"author": "王安石","era": "《臨川先生文集》",   "dynasty": "宋文"},
    "shang-zhongyong":       {"author": "王安石", "era": "《臨川先生文集》",    "dynasty": "宋文"},
    # 曾鞏補充
    "ji-ouyang-sheren-shu":  {"author": "曾鞏",   "era": "《元豐類稿》",        "dynasty": "宋文"},
    "zeng-lian-ersheng-xu":  {"author": "曾鞏",   "era": "《元豐類稿》",        "dynasty": "宋文"},
    "taizhou-hailing-xuzhu-muzhi":{"author": "曾鞏","era": "《元豐類稿》",      "dynasty": "宋文"},
    # 其他宋文
    "song-dongyang":         {"author": "宋濂",   "era": "《宋文憲公全集》",    "dynasty": "明文"},
    "lianchi":               {"author": "顧炎武", "era": "《日知錄》",          "dynasty": "清文"},
    "xiangling":             {"author": "歸有光", "era": "《震川先生集》",       "dynasty": "明文"},
    "hongmen":               {"author": "司馬遷", "era": "《史記·項羽本紀》",   "dynasty": "漢文"},
    "goujian":               {"author": "左丘明", "era": "《國語·越語上》",     "dynasty": "周文"},

    # ── 明文 ─────────────────────────────────────────────────────────────────
    "maigan":                {"author": "劉基",   "era": "《誠意伯文集》",      "dynasty": "明文"},
    "wuren-mubei":           {"author": "張溥",   "era": "《七錄齋集》",        "dynasty": "明文"},
    "send-tiantai-chentingxue-xu":{"author": "宋濂","era": "《宋文憲公全集》",  "dynasty": "明文"},
    "song-tiantai-chentingxue-xu":{"author": "宋濂","era": "《宋文憲公全集》",  "dynasty": "明文"},
    "yuejiang-lou-ji":       {"author": "朱元璋", "era": "《明太祖文集》",      "dynasty": "明文"},
    "sima-jizhu-lun-bu":     {"author": "劉基",   "era": "《誠意伯文集》",      "dynasty": "明文"},
    "shenlu-lun":            {"author": "方孝孺", "era": "《遜志齋集》",        "dynasty": "明文"},
    "yurang-lun":            {"author": "方孝孺", "era": "《遜志齋集》",        "dynasty": "明文"},
    "qinzheng-pian":         {"author": "王鏊",   "era": "《震澤集》",          "dynasty": "明文"},
    "zunjing-ge-ji":         {"author": "王守仁", "era": "《王文成公全書》",    "dynasty": "明文"},
    "xiang-ci-ji":           {"author": "王守仁", "era": "《王文成公全書》",    "dynasty": "明文"},
    "xinlingjun-jiu-zhao-lun":{"author": "唐順之","era": "《荊川集》",          "dynasty": "明文"},
    "bao-liu-yi-zhang-shu":  {"author": "宗臣",   "era": "《宗子相集》",        "dynasty": "明文"},
    "wushan-tu-ji":          {"author": "歸有光", "era": "《震川先生集》",       "dynasty": "明文"},
    "canglang-ting-ji":      {"author": "歸有光", "era": "《震川先生集》",       "dynasty": "明文"},
    "qingxia-xiansheng-wenji-xu":{"author": "茅坤","era": "《茅鹿門文集》",     "dynasty": "明文"},
    "linxiangru-wanbi-guizhao-lun":{"author": "王世貞","era": "《弇州山人四部稿》","dynasty": "明文"},
    "xu-wenchang-zhuan":     {"author": "袁宏道", "era": "《袁中郎全集》",      "dynasty": "明文"},

    # ── 其他補充 ──────────────────────────────────────────────────────────────
    "wangyucheng-dai-lou":   {"author": "王禹偁", "era": "《小畜集》",          "dynasty": "宋文"},
    "wushan-ji":             {"author": "歸有光", "era": "《震川先生集》",       "dynasty": "明文"},
}

# Maps author name → biographical info
AUTHOR_INFO = {
    "左丘明": {
        "full_name": "左丘明（約前502—前422）",
        "courtesy": "魯國史官",
        "dynasty": "周",
        "intro": "春秋末期魯國史官，著《左傳》與《國語》，是中國敘事散文的奠基者，所記史事詳贍，文字生動。",
    },
    "公羊高": {
        "full_name": "公羊高（戰國時人）",
        "courtesy": "子夏弟子",
        "dynasty": "周",
        "intro": "戰國時齊人，傳《春秋公羊傳》，以義理詮釋《春秋》，為今文經學之宗。",
    },
    "穀梁赤": {
        "full_name": "穀梁赤（戰國時人）",
        "courtesy": "子夏弟子",
        "dynasty": "周",
        "intro": "戰國時魯人，傳《春秋穀梁傳》，解經簡練，重名分義理，為今文三傳之一。",
    },
    "戴聖": {
        "full_name": "戴聖（西漢，生卒年不詳）",
        "courtesy": "字次君",
        "dynasty": "漢",
        "intro": "西漢禮學家，編訂《禮記》（小戴禮記），保存了大量先秦儒家典禮及思想資料。",
    },
    "劉向": {
        "full_name": "劉向（前77—前6）",
        "courtesy": "字子政，本名更生",
        "dynasty": "漢",
        "intro": "西漢學者、目錄學家，整理編訂《戰國策》《說苑》《列女傳》等，文辭典雅。",
    },
    "屈原": {
        "full_name": "屈原（約前340—前278）",
        "courtesy": "名平，字原，又字靈均",
        "dynasty": "楚",
        "intro": "戰國楚國詩人與政治家，創楚辭體，代表作《離騷》，投汨羅江而死，後世奉為愛國詩人。",
    },
    "宋玉": {
        "full_name": "宋玉（約前298—約前222）",
        "courtesy": "字子淵",
        "dynasty": "楚",
        "intro": "戰國末楚國辭賦家，屈原之後，善寫豔麗之辭，代表作《九辯》《高唐賦》。",
    },
    "樂毅": {
        "full_name": "樂毅（戰國，生卒年不詳）",
        "courtesy": "燕國名將",
        "dynasty": "周",
        "intro": "戰國燕國名將，率五國聯軍伐齊，幾滅齊國，後受讒奔趙，所作《報燕惠王書》情理兼勝。",
    },
    "李斯": {
        "full_name": "李斯（約前280—前208）",
        "courtesy": "楚上蔡人，秦丞相",
        "dynasty": "秦",
        "intro": "秦朝丞相，輔助秦始皇統一六國，書法精美，《諫逐客書》為先秦說理散文名篇。",
    },
    "司馬遷": {
        "full_name": "司馬遷（約前145—約前87）",
        "courtesy": "字子長，世稱太史公",
        "dynasty": "漢",
        "intro": "西漢歷史學家，撰《史記》，開紀傳體先例，魯迅譽為「史家之絕唱，無韻之離騷」。",
    },
    "劉邦": {
        "full_name": "劉邦（前256—前195）",
        "courtesy": "字季，漢高祖",
        "dynasty": "漢",
        "intro": "漢朝開國皇帝，由平民起義推翻秦朝，建立漢朝，其求賢詔文辭質樸而氣勢宏大。",
    },
    "劉恆": {
        "full_name": "劉恆（前202—前157）",
        "courtesy": "漢文帝",
        "dynasty": "漢",
        "intro": "西漢第三位皇帝，施行仁政，與漢景帝共創「文景之治」，其詔令體現愛民之風。",
    },
    "劉啟": {
        "full_name": "劉啟（前188—前141）",
        "courtesy": "漢景帝",
        "dynasty": "漢",
        "intro": "西漢第六位皇帝，繼文帝仁政，輕徭薄賦，重農桑，其詔令簡明扼要。",
    },
    "劉徹": {
        "full_name": "劉徹（前156—前87）",
        "courtesy": "漢武帝",
        "dynasty": "漢",
        "intro": "西漢第七位皇帝，在位期間開疆拓土，建立盛世，其求賢詔語氣積極進取。",
    },
    "賈誼": {
        "full_name": "賈誼（前200—前168）",
        "courtesy": "字太傅，洛陽人",
        "dynasty": "漢",
        "intro": "西漢政論家與文學家，少有才名，著《過秦論》《治安策》，分析時政深刻犀利。",
    },
    "晁錯": {
        "full_name": "晁錯（前200—前154）",
        "courtesy": "字不詳，潁川人",
        "dynasty": "漢",
        "intro": "西漢政治家，力主削藩，後被殺，《論貴粟疏》重農抑商思想影響深遠。",
    },
    "鄒陽": {
        "full_name": "鄒陽（西漢，生卒年不詳）",
        "courtesy": "齊人",
        "dynasty": "漢",
        "intro": "西漢文學家，善辯，因遭讒入獄，上書梁王自明，文辭引典豐富，邏輯嚴密。",
    },
    "司馬相如": {
        "full_name": "司馬相如（約前179—前117）",
        "courtesy": "字長卿，蜀郡成都人",
        "dynasty": "漢",
        "intro": "西漢辭賦大家，代表作《子虛賦》《上林賦》，其上書諫獵體現儒家民本思想。",
    },
    "李陵": {
        "full_name": "李陵（？—前74）",
        "courtesy": "字少卿，隴西成紀人",
        "dynasty": "漢",
        "intro": "西漢名將，投降匈奴後作《答蘇武書》，敘亡命之苦，情真意切，為漢代書牘名篇。",
    },
    "路溫舒": {
        "full_name": "路溫舒（西漢，生卒年不詳）",
        "courtesy": "字長君，鉅鹿人",
        "dynasty": "漢",
        "intro": "西漢法律家，上書宣帝請求寬刑，《尚德緩刑書》為漢代刑法改革重要文獻。",
    },
    "楊惲": {
        "full_name": "楊惲（？—前54）",
        "courtesy": "字子幼，楊敞之子",
        "dynasty": "漢",
        "intro": "西漢大臣，因書信言辭激烈獲罪被殺，《報孫會宗書》抒憤懣之情，真情流露。",
    },
    "劉秀": {
        "full_name": "劉秀（前5—57）",
        "courtesy": "光武帝，字文叔",
        "dynasty": "漢",
        "intro": "東漢開國皇帝，中興漢室，《臨淄勞耿弇》短文展現帝王對功臣的體恤之情。",
    },
    "馬援": {
        "full_name": "馬援（前14—49）",
        "courtesy": "字文淵，扶風茂陵人",
        "dynasty": "漢",
        "intro": "東漢名將，《誡兄子嚴敦書》教以處世謙遜之道，文字懇切，為家書典範。",
    },
    "諸葛亮": {
        "full_name": "諸葛亮（181—234）",
        "courtesy": "字孔明，號臥龍",
        "dynasty": "三國",
        "intro": "蜀漢丞相，輔佐劉備與劉禪，《出師表》情辭懇切，千古傳誦，忠君報國之典範。",
    },
    "李密": {
        "full_name": "李密（224—287）",
        "courtesy": "字令伯，犍為武陽人",
        "dynasty": "晉",
        "intro": "西晉文學家，《陳情表》婉辭拒絕仕晉，以孝事祖母感人至深，列為孝文典範。",
    },
    "王羲之": {
        "full_name": "王羲之（303—361）",
        "courtesy": "字逸少，琅琊臨沂人",
        "dynasty": "晉",
        "intro": "東晉書法家，被譽為「書聖」，《蘭亭集序》為天下第一行書，文章亦清俊雋永。",
    },
    "陶淵明": {
        "full_name": "陶淵明（365—427）",
        "courtesy": "字元亮，號五柳先生",
        "dynasty": "晉",
        "intro": "東晉詩人，田園詩派之祖，辭官歸隱，《歸去來辭》《桃花源記》為歸隱文學典範。",
    },
    "孔稚珪": {
        "full_name": "孔稚珪（447—501）",
        "courtesy": "字德璋，會稽山陰人",
        "dynasty": "南齊",
        "intro": "南朝齊文學家，《北山移文》以山為口假借山神之言諷刺偽隱士，文辭瑰麗奇特。",
    },
    "魏徵": {
        "full_name": "魏徵（580—643）",
        "courtesy": "字玄成，鉅鹿曲城人",
        "dynasty": "唐",
        "intro": "唐初政治家，太宗重臣，以直諫著稱，《諫太宗十思疏》為唐代政論文名篇。",
    },
    "駱賓王": {
        "full_name": "駱賓王（約640—約684）",
        "courtesy": "字觀光，婺州義烏人",
        "dynasty": "唐",
        "intro": "初唐詩人，「初唐四傑」之一，《為徐敬業討武曌檄》氣勢磅礴，為檄文典範。",
    },
    "王勃": {
        "full_name": "王勃（649—676）",
        "courtesy": "字子安，絳州龍門人",
        "dynasty": "唐",
        "intro": "初唐詩人，「初唐四傑」之首，《滕王閣序》詞采飛揚，是唐代駢文的巔峰之作。",
    },
    "李白": {
        "full_name": "李白（701—762）",
        "courtesy": "字太白，號青蓮居士",
        "dynasty": "唐",
        "intro": "唐代浪漫主義詩人，「詩仙」，文章亦豪放不羈，《與韓荊州書》自薦之作氣魄非凡。",
    },
    "李華": {
        "full_name": "李華（約715—約766）",
        "courtesy": "字遐叔，趙州贊皇人",
        "dynasty": "唐",
        "intro": "唐代文學家，古文運動先驅，《弔古戰場文》哀悼陣亡將士，文辭悲壯雄健。",
    },
    "劉禹錫": {
        "full_name": "劉禹錫（772—842）",
        "courtesy": "字夢得，洛陽人",
        "dynasty": "唐",
        "intro": "唐代文學家，被稱為「詩豪」，《陋室銘》以銘文體抒高潔志趣，膾炙人口。",
    },
    "杜牧": {
        "full_name": "杜牧（803—852）",
        "courtesy": "字牧之，號樊川居士",
        "dynasty": "唐",
        "intro": "晚唐詩人，與李商隱並稱「小李杜」，《阿房宮賦》借古諷今，警示統治者勿驕奢。",
    },
    "韓愈": {
        "full_name": "韓愈（768—824）",
        "courtesy": "字退之，世稱韓昌黎",
        "dynasty": "唐",
        "intro": "唐代文學家，古文運動領袖，唐宋八大家之首，倡文以載道，《師說》《原道》影響深遠。",
    },
    "柳宗元": {
        "full_name": "柳宗元（773—819）",
        "courtesy": "字子厚，世稱柳河東",
        "dynasty": "唐",
        "intro": "唐代文學家，古文運動主將，唐宋八大家之一，山水遊記獨樹一幟，寓意深刻。",
    },
    "王禹偁": {
        "full_name": "王禹偁（954—1001）",
        "courtesy": "字元之，鉅野人",
        "dynasty": "宋",
        "intro": "北宋文學家，學習韓柳古文，倡平易文風，《黃岡竹樓記》清淡自適，開宋文一代風氣。",
    },
    "王褒": {
        "full_name": "王褒（約513—576）",
        "courtesy": "字子淵，琅琊臨沂人",
        "dynasty": "北周",
        "intro": "北周文學家，南北朝文士，《瘞旅文》文辭凄婉，為哀祭文名篇。",
    },
    "范仲淹": {
        "full_name": "范仲淹（989—1052）",
        "courtesy": "字希文，蘇州人",
        "dynasty": "宋",
        "intro": "北宋政治家、文學家，《岳陽樓記》「先天下之憂而憂」為千古名句，精神感召後世。",
    },
    "歐陽修": {
        "full_name": "歐陽修（1007—1072）",
        "courtesy": "字永叔，號醉翁，又號六一居士",
        "dynasty": "宋",
        "intro": "北宋文學家，唐宋八大家之一，倡宋代古文革新，《醉翁亭記》《秋聲賦》傳誦千古。",
    },
    "蘇洵": {
        "full_name": "蘇洵（1009—1066）",
        "courtesy": "字明允，號老泉",
        "dynasty": "宋",
        "intro": "北宋文學家，「三蘇」之父，唐宋八大家之一，《六國論》縱橫捭闔，論辯有力。",
    },
    "蘇軾": {
        "full_name": "蘇軾（1037—1101）",
        "courtesy": "字子瞻，號東坡居士",
        "dynasty": "宋",
        "intro": "北宋文學家、書畫家，唐宋八大家之一，《前赤壁賦》《石鐘山記》文情並茂，曠達超然。",
    },
    "蘇轍": {
        "full_name": "蘇轍（1039—1112）",
        "courtesy": "字子由，號潁濱遺老",
        "dynasty": "宋",
        "intro": "北宋文學家，唐宋八大家之一，「三蘇」之一，文風沉鬱，《黃州快哉亭記》記景寓志。",
    },
    "王安石": {
        "full_name": "王安石（1021—1086）",
        "courtesy": "字介甫，號半山",
        "dynasty": "宋",
        "intro": "北宋政治家、文學家，唐宋八大家之一，主持「熙寧變法」，《讀孟嘗君傳》議論精闢。",
    },
    "曾鞏": {
        "full_name": "曾鞏（1019—1083）",
        "courtesy": "字子固，南豐人",
        "dynasty": "宋",
        "intro": "北宋文學家，唐宋八大家之一，文章謹嚴典雅，《寄歐陽舍人書》體現其文學主張。",
    },
    "司馬光": {
        "full_name": "司馬光（1019—1086）",
        "courtesy": "字君實，號迂叟",
        "dynasty": "宋",
        "intro": "北宋政治家、史學家，著《資治通鑑》，反對王安石變法，文章平實嚴謹。",
    },
    "范仲淹": {
        "full_name": "范仲淹（989—1052）",
        "courtesy": "字希文，吳縣人",
        "dynasty": "宋",
        "intro": "北宋政治家、文學家，《岳陽樓記》「先天下之憂而憂，後天下之樂而樂」為千古名句。",
    },
    "李覯": {
        "full_name": "李覯（1009—1059）",
        "courtesy": "字泰伯，南城人",
        "dynasty": "宋",
        "intro": "北宋思想家，學術著作豐富，《袁州州學記》記重修州學之事，論說學校教化之重要。",
    },
    "李格非": {
        "full_name": "李格非（約1045—約1105）",
        "courtesy": "字文叔，章丘人",
        "dynasty": "宋",
        "intro": "北宋文學家，李清照之父，《洛陽名園記》記園廢而感興亡，寓論深刻。",
    },
    "劉基": {
        "full_name": "劉基（1311—1375）",
        "courtesy": "字伯溫，號犁眉公",
        "dynasty": "明",
        "intro": "明朝開國功臣，文學家，《賣柑者言》寓言諷刺官員外美內腐，《司馬季主論卜》議論精微。",
    },
    "宋濂": {
        "full_name": "宋濂（1310—1381）",
        "courtesy": "字景濂，號潛溪",
        "dynasty": "明",
        "intro": "明初文學家，被朱元璋稱為「開國文臣之首」，《送東陽馬生序》勸學篇，述艱難求學之樂。",
    },
    "朱元璋": {
        "full_name": "朱元璋（1328—1398）",
        "courtesy": "明太祖，字國瑞",
        "dynasty": "明",
        "intro": "明朝開國皇帝，出身貧苦，推翻元朝，《閱江樓記》記建樓之義，氣象宏偉。",
    },
    "方孝孺": {
        "full_name": "方孝孺（1357—1402）",
        "courtesy": "字希直，一字希古",
        "dynasty": "明",
        "intro": "明初文學家，忠於建文帝，燕王靖難後拒不起草詔書而被誅十族，氣節凜然。",
    },
    "王鏊": {
        "full_name": "王鏊（1450—1524）",
        "courtesy": "字濟之，號守溪",
        "dynasty": "明",
        "intro": "明代文學家，官至大學士，文章古雅醇厚，《親政篇》論君主親政之道，條理分明。",
    },
    "王守仁": {
        "full_name": "王守仁（1472—1529）",
        "courtesy": "字伯安，號陽明",
        "dynasty": "明",
        "intro": "明代哲學家、軍事家，心學集大成者，《象祠記》《尊經閣記》寓哲學思想於記文之中。",
    },
    "唐順之": {
        "full_name": "唐順之（1507—1560）",
        "courtesy": "字應德，號荊川",
        "dynasty": "明",
        "intro": "明代文學家，唐宋派代表人物，《信陵君救趙論》論史精辟，見解獨特。",
    },
    "宗臣": {
        "full_name": "宗臣（1525—1560）",
        "courtesy": "字子相，興化人",
        "dynasty": "明",
        "intro": "明代文學家，後七子之一，《報劉一丈書》揭露官場醜態，諷刺辛辣，情感真摯。",
    },
    "歸有光": {
        "full_name": "歸有光（1507—1571）",
        "courtesy": "字熙甫，號震川",
        "dynasty": "明",
        "intro": "明代散文家，唐宋派代表，以清淡平易著稱，《項脊軒志》追憶家事，感人至深。",
    },
    "茅坤": {
        "full_name": "茅坤（1512—1601）",
        "courtesy": "字順甫，號鹿門",
        "dynasty": "明",
        "intro": "明代文學家，編選《唐宋八大家文鈔》，對唐宋古文的流傳有重要貢獻。",
    },
    "王世貞": {
        "full_name": "王世貞（1526—1590）",
        "courtesy": "字元美，號鳳洲",
        "dynasty": "明",
        "intro": "明代文學家，後七子領袖，《藺相如完璧歸趙論》翻案立論，見解獨到新穎。",
    },
    "袁宏道": {
        "full_name": "袁宏道（1568—1610）",
        "courtesy": "字中郎，號石公",
        "dynasty": "明",
        "intro": "明代文學家，公安派領袖，主「獨抒性靈，不拘格套」，《徐文長傳》為傳記文名篇。",
    },
    "張溥": {
        "full_name": "張溥（1602—1641）",
        "courtesy": "字天如，號西銘",
        "dynasty": "明",
        "intro": "明末文學家，復社創始人，《五人墓碑記》為明末市民反抗閹黨的歷史留下珍貴記錄。",
    },
    "顧炎武": {
        "full_name": "顧炎武（1613—1682）",
        "courtesy": "字寧人，號亭林",
        "dynasty": "清",
        "intro": "明末清初思想家、學者，反對空談心性，主實學，《廉恥》論士大夫節操之重要。",
    },
    "召公": {
        "full_name": "召公（西周，生卒年不詳）",
        "courtesy": "姬奭，召伯",
        "dynasty": "周",
        "intro": "西周大臣，輔佐文王、武王、成王，廉潔愛民，諫厲王止謗，為西周政論名篇。",
    },
}
